<?php
/**
 * Created by PhpStorm.
 * User: leodaniel
 * Date: 06.01.18
 * Time: 10:12
 */

namespace le0daniel\System\Console\Commands;

use Carbon\Carbon;
use le0daniel\System\Helpers\Path;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Exception\RuntimeException;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\ChoiceQuestion;
use Symfony\Component\Console\Question\Question;

class GenereatePotFile extends Command {

	/**
	 * Regex to parse twig templates
	 *
	 * @var string
	 */
	//protected $regex = '/{{\s*\'(?<t>.*?)\'\s*\|\s*t(?:.*?)}}/';
	protected $regex = '/{{\s*([\'"])(?<t>.*?)\1\s*\|\s*t(?:.*?)}}/';



	protected function configure()
	{
		$this
			->setName('generate:pot')
			->setDescription('This command should only be runned once')
			->setHelp('This command allows you to generate all files needed when creating a new Theme');
	}

	/**
	 * @param InputInterface $input
	 * @param OutputInterface $output
	 *
	 * @return void
	 */
	protected function execute(InputInterface $input, OutputInterface $output){

		$files = Path::find_recursive(
			Path::activeThemePath('resources/views/*.twig')
		);

		$total_keys = [];

		foreach($files as $file){

			$content = file_get_contents($file);
			preg_match_all($this->regex, $content, $matches, PREG_SET_ORDER, 0);
			$keys = array_column($matches,'t');

			$total_keys[basename($file)] = $keys;
			unset($content);
		}

		$compiled_elements = [];

		/* Generate translation file */
		foreach($total_keys as $filename => $keys){

			/* Compile all elements */
			foreach($keys as $key){
				$compiled_elements[] = $this->compileElement($filename,$key);
			}

		}

		$this->generateFile($compiled_elements);

	}

	/**
	 * @param string $file
	 * @param string $key
	 *
	 * @return string
	 */
	protected function compileElement(string $file,string $key){

		return implode(PHP_EOL,[
			sprintf('#: %s',$file),
			sprintf('msgid "%s"', addslashes( $key ) ),
			'msgstr ""',
		]);
	}

	/**
	 * @param array $elements
	 */
	protected function generateFile(array $elements){
		/* Get save path */
		$save_path = Path::activeThemePath('resources/lang/'.Path::$theme_dirname.'.pot');

		if(file_exists($save_path)){
			$save_path = $save_path.Carbon::now()->format('Ymd_His').'.pot';
		}

		$header = implode(PHP_EOL,[
			'# Generated by Nitrosoft WP_system',
			'# Autogenerated, take with caution!',
			'msgid ""',
			'msgstr ""',
		]);

		$rendered = implode(PHP_EOL,$elements);

		$file = $header.PHP_EOL.$rendered;

		file_put_contents($save_path,$file);
	}

}